const sessions=[{name:'Sydney',tz:'Australia/Sydney',hours:'22:00–07:00'},{name:'Tokyo',tz:'Asia/Tokyo',hours:'00:00–09:00'},{name:'London',tz:'Europe/London',hours:'08:00–17:00'},{name:'New York',tz:'America/New_York',hours:'13:00–22:00'}];
const demoNews=[{time:'14:30',impact:'HIGH',title:'USD — Major economic release',meta:'Demo calendar event'},{time:'16:00',impact:'MEDIUM',title:'USD — Economic data',meta:'Demo calendar event'},{time:'18:30',impact:'LOW',title:'EUR — Scheduled release',meta:'Demo calendar event'}];
const demoRegime={score:82,name:'BULLISH / STRONG',text:'Demo state — live ADX, ATR, EMA and price data required.',trend:'BUY',adx:'32.6',atr:'1.24 (NORMAL)',volatility:'LOW',ema:'BULLISH (20 > 50 > 200)'};
function nowIn(tz){return new Date(new Date().toLocaleString('en-US',{timeZone:tz}))}
function isOpen(s){const d=nowIn(s.tz),mins=d.getHours()*60+d.getMinutes();const [a,b]=s.hours.split('–').map(x=>{const [h,m]=x.split(':').map(Number);return h*60+m});return a<b?mins>=a&&mins<b:mins>=a||mins<b}
function updateClock(){const d=new Date();document.getElementById('clock').textContent=d.toLocaleTimeString('en-GB',{timeZone:'Asia/Colombo'});document.getElementById('date').textContent=d.toLocaleDateString('en-GB',{timeZone:'Asia/Colombo',weekday:'long',day:'2-digit',month:'long',year:'numeric'});const open=sessions.filter(isOpen),overlap=open.length>1;document.getElementById('session').textContent=overlap?'SESSION OVERLAP':(open[0]?.name.toUpperCase()||'MARKET CLOSED');document.getElementById('sessionDetail').textContent=open.length?open.map(x=>x.name).join(' + '):'No major session currently open';renderSessions()}
function renderSessions(){document.getElementById('sessionGrid').innerHTML=sessions.map(s=>`<div class="session ${isOpen(s)?'active':''}"><div class="session-name">${s.name}</div><div class="session-time">${s.hours}</div><div class="session-state ${isOpen(s)?'ok':''}">${isOpen(s)?'● OPEN':'○ CLOSED'}</div></div>`).join('')}
function renderNews(){document.getElementById('newsList').innerHTML=demoNews.map(n=>`<div class="news"><div class="impact ${n.impact==='HIGH'?'high':n.impact==='MEDIUM'?'medium':'low'}">${n.impact}</div><div><div class="news-title">${n.title}</div><div class="news-meta">${n.meta}</div></div><b>${n.time}</b></div>`).join('');const high=demoNews.some(n=>n.impact==='HIGH');document.getElementById('newsRisk').textContent=high?'HIGH IMPACT':'LOW RISK';document.getElementById('newsRisk').className='badge '+(high?'warn':'ok')}
function renderDecision(){for(const [id,val] of Object.entries({regimeScore:demoRegime.score,regimeName:demoRegime.name,regimeText:demoRegime.text,trend:demoRegime.trend,adx:demoRegime.adx,atr:demoRegime.atr,volatility:demoRegime.volatility,ema:demoRegime.ema}))document.getElementById(id).textContent=val;document.getElementById('regimeBadge').textContent='DEMO';document.getElementById('overallScore').textContent=demoRegime.score;document.getElementById('scoreTrend').textContent='85';document.getElementById('scoreMomentum').textContent='88';document.getElementById('scoreNews').textContent='55';const high=demoNews.some(n=>n.impact==='HIGH'),sessionOpen=sessions.some(isOpen);let state='warn',decision='CAUTION',reason='Conditions are mixed. Wait for better confirmation.';if(!high&&sessionOpen&&demoRegime.score>=75){state='good';decision='GOOD TO TRADE';reason='All conditions are favorable. Look for high-quality setups.'}else if(high){state='bad';decision='AVOID TRADE';reason='High-impact news risk detected. Avoid fresh entries around major releases.'}document.body.className='state-'+state;document.getElementById('marketStatus').textContent=decision;document.getElementById('marketStatusDetail').textContent=reason;document.getElementById('decision').textContent=decision;document.getElementById('decision').className='decision '+state;document.getElementById('dSession').textContent=sessionOpen?'OPEN':'CLOSED';document.getElementById('dNews').textContent=high?'HIGH RISK':'LOW';document.getElementById('dRegime').textContent=demoRegime.score+'/100';document.getElementById('entryQuality').textContent=demoRegime.score>=75?'GOOD':'WEAK';document.getElementById('decisionReason').textContent=reason}
let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;document.getElementById('installBtn').hidden=false});document.getElementById('installBtn').addEventListener('click',async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;document.getElementById('installBtn').hidden=true});window.addEventListener('appinstalled',()=>document.getElementById('installBtn').hidden=true);if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.error));updateClock();renderNews();renderDecision();setInterval(updateClock,1000);setInterval(renderDecision,30000);
